 apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobswatch
  namespace: default
spec:
  selector:
    matchLabels:
      app: jobswatch
  replicas: 3
  template:
    metadata:
      labels:
        app: jobswatch
    spec:
      containers:
        - name: jobswatch
          image: eng103ayeye/eng103a_project
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jobswatch
spec:
  ports:
  - nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jobswatch
  type: NodePort
